name: admin_rental_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.17.0
  cloud_firestore: ^3.1.15
  firebase_storage: ^10.2.16
  intl: ^0.17.0
  firebase_auth: ^3.3.18
  image_picker: ^0.8.5+3
  url_launcher: ^6.1.2
  easy_image_viewer: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: SFThonburi
      fonts:
        - asset: assets/fonts/SFThonburi-Regular.ttf
        - asset: assets/fonts/SFThonburi-Bold.ttf
          weight: 700
        - asset: assets/fonts/SFThonburi-Semibold.ttf
          weight: 600
