name: admin_rental_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.13.1
  cloud_firestore: ^3.1.10
  firebase_storage: ^10.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

  fonts:
    - family: SFThonburi
      fonts:
        - asset: assets/fonts/SFThonburi-Regular.ttf
        - asset: assets/fonts/SFThonburi-Bold.ttf
          weight: 700
        - asset: assets/fonts/SFThonburi-Semibold.ttf
          weight: 600
